server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://119.23.210.155:3306/mayan?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
